Gui:
    Game Name: "J League Winning Eleven 2009 Club Championship"

option_file_data:
    Game Identifier : [
        "BISLPM-551822009OPT",
    ]
    ENCRYPTED : True    
    OF_BYTE_LENGTH : 1024000
    OF_BLOCK : [
        12,
        5144,
        9544,
        16976,
        39804,
        613524,
        690636,
        710612,
        848688,
        1004324,
    ]
    OF_BLOCK_SIZE : [
        4868,
        1268,
        7420,
        22816,
        572880,
        77100,
        19964,
        138064,
        155624,
        19428,
    ]

Player:
    First Unused : 4616

Teams:
    Total Nations : 0
    Total Classic : 0
    Total J Nations : 0
    Total J Clubs : 3
    J League Extra Clubs : 55
    Max Players In Nations : 23
    Max Players In Clubs : 32
    Separator Size : 0

Club:
    Size : 92
    Max Abbr Name Size : 10
    First Emblem : 356
    First Club Emblem : 120

Stadiums:
    Total : 55
    Max Lenght : 73

Leagues:
    Total : 39

Kits:
    Nation Kit Data Size : 0
    Club Kit Data Size : 552
    Kit Data Size : 64

Shop:
    Points Offset : 5216
    Has Background Selector : True
    Total Backgrounds : 63

NATIONS : [
    "Japan",
    "England",
    "France",
    "Italy",
    "Netherlands",
    "Spain",
    "Belgium",
    "Greece",
    "Portugal",
    "Scotland",
    "Serbia",
    "Switzerland",
    "Turkey",
    "Ukraine",
    "Argentina",
    "Brazil",
    "Australia",
    "China",
    "Korea",
    "Indonesia",
    "Singapore",
    "Iran",
    "Qatar",
    "Saudi Arabia",
    "UAE",
    "Uzbekistan",
    "Costa Rica",
    "Mexico",
    "United States",
    "New Zealand",
    "Papua New Guinea",
    "Nigeria",
    "South Africa",
    "Algeria",
    "Albania",
    "Andorra",
    "Armenia",
    "Austria",
    "Azerbaijan",
    "Belarus",
    "Bosnia-Herzegovina",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czech",
    "Denmark",
    "Estonia",
    "Faroe Islands",
    "Finland",
    "Georgia",
    "Germany",
    "Hungary",
    "Iceland",
    "Ireland",
    "Israel",
    "Kazakhstan",
    "Latvia",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macedonia",
    "Malta",
    "Moldova",
    "Montenegro",
    "Northern Ireland",
    "Norway",
    "Poland",
    "Romania",
    "Russia",
    "San Marino",
    "Slovakia",
    "Slovenia",
    "Sweden",
    "Wales",
    "Yugoslavia",
    "Angola",
    "Benin",
    "Burkina Faso",
    "Burundi",
    "Cameroon",
    "Cape Verde",
    "Central Africa",
    "Chad",
    "Republic of the Congo",
    "Cote d'Ivoire",
    "Democratic Republic of the Congo",
    "Egypt",
    "Equatorial Guinea",
    "Gabon",
    "Gambia",
    "Ghana",
    "Guinea",
    "Guinea-Bissau",
    "Kenya",
    "Liberia",
    "Libya",
    "Mali",
    "Morocco",
    "Mozambique",
    "Rwanda",
    "Senegal",
    "Sierra Leone",
    "Togo",
    "Tunisia",
    "Zambia",
    "Zimbabwe",
    "Barbados",
    "Canada",
    "Grenada",
    "Guadeloupe",
    "Haiti",
    "Honduras",
    "Jamaica",
    "Martinique",
    "Netherlands Antilles",
    "Panama",
    "Republic of Trinidad and Tobago",
    "Bolivia",
    "Chile",
    "Columbia",
    "Ecuador",
    "Paraguay",
    "Peru",
    "Uruguay",
    "Venezuela",
    "Bahrain",
    "Iraq",
    "Kuwait",
    "Malaysia",
    "north korea",
    "Oman",
    "Syria",
    "Thailand",
    "Vietnam",
    "Solomon Islands",
    "Free Nationality",
]



CLASSIC TEAMS : [
"Classic England",
"Classic France",
"Classic Germany",
"Classic Italy",
"Classic Netherlands",
"Classic Argentina",
"Classic Brazil",
]

GROWTH TYPES:

    EARLY: [
        128,
        130,
        141,
        146,
        149,
        154,
        164,
        166,
        168,
        170,
        174,
        175,
        176,
        178,
        188,
        190,
        210,
        212,
        244,
        248,
        0,
        9,
        49,
        105,
        118,
        123,
        124,
        126,
    ]

    EARLY LASTING : [
        136,
        142,
        148,
        161,
        172,
        173,
        189,
        193,
        202,
        204,
        220,
        242,
        247,
        25,
        51,
        67,
        70,
        82,
        88,
        89,
        107,
        121,
        127,
    ]

    STANDARD : [
        132,
        139,
        144,
        145,
        147,
        150,
        152,
        153,
        155,
        159,
        162,
        165,
        169,
        177,
        179,
        180,
        181,
        183,
        187,
        192,
        194,
        198,
        200,
        201,
        203,
        208,
        213,
        214,
        221,
        231,
        234,
        235,
        239,
        243,
        245,
        246,
        249,
        1,
        3,
        4,
        6,
        12,
        16,
        18,
        19,
        20,
        26,
        28,
        29,
        30,
        31,
        40,
        42,
        52,
        53,
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        61,
        62,
        63,
        65,
        68,
        69,
        72,
        73,
        74,
        75,
        76,
        77,
        78,
        79,
        80,
        83,
        84,
        85,
        87,
        94,
        95,
        97,
        100,
        101,
        104,
        106,
        112,
        114,
        115,
        116,
        119,
        120,
        122,
        125,

    ]

    STANDARD LASTING : [
        129,
        131,
        135,
        138,
        143,
        151,
        160,
        182,
        186,
        191,
        195,
        196,
        211,
        216,
        223,
        227,
        230,
        237,
        240,
        251,
        5,
        7,
        11,
        13,
        14,
        15,
        23,
        32,
        34,
        36,
        38,
        47,
        48,
        81,
        91,
        92,
        96,
        99,
        108,
        110,
        113,
    ]

    LATE : [
        133,
        137,
        140,
        156,
        157,
        158,
        163,
        171,
        184,
        185,
        199,
        206,
        207,
        209,
        215,
        217,
        219,
        218,
        225,
        232,
        233,
        238,
        241,
        252,
        2,
        8,
        17,
        21,
        22,
        33,
        35,
        37,
        39,
        43,
        44,
        46,
        64,
        66,
        71,
        86,
        93,
        98,
        102,
        103,
        109,
        111,
        117,
    ]

    LATE LASTING : [
        134,
        167,
        197,
        205,
        224,
        228,
        250,
        253,
        254,
        10,
        24,
        41,
        90,
    ]



